spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
  redis:
    database: 10
    host: 192.168.0.200
    port: 6379
    password:

mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.dlh.mybatis.dao: debug